version: '3'
services:
  app:
    image: ${REPO}/app:${TAG}
    env_file:
      - ../env.list
    environment:
      - ENV=${ENV}
      - SSL=${SSL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /go/src/haha/cmd/
    ports:
      - "8080:8080"
    network_mode: host