version: '3'
services:
  db:
    image: postgres:12.6
    restart: always
    volumes:
      - ./pkg/infrastructure/postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../env.list

  app:
    image: ${REPO}/app:${TAG}
    restart: unless-stopped
    env_file:
      - ../env.list
    depends_on:
      - db
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /go/src/haha/cmd/
    ports:
      - "8080:8080"
    network_mode: host
