name: Build production

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test with cover
        run: make test-cover

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        run: |
          docker build \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/app:latest \
          -f docker/app.Dockerfile . \
      - name: Push the images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:${GITHUB_SHA::8}